name: Docker Push DHCPH6 image

on:
  push:
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}:v2307


jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Docker Login
        run: echo "${{ secrets.GB_DHCPD6_TOKEN }}" | docker login ${{ REGISTRY }} --username cloud-native-everything --password-stdin
     
      - name: Docker Build
        run: docker build -t ${{ REGISTRY }}/${{ IMAGE_NAME }} .
        
      - name: Docker Push
        run: docker push  ${{ REGISTRY }}/${{ IMAGE_NAME }}

